kidznextdoor/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
]

main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'
urlpatterns = [
    # http://localhost/
    url(r'^$', views.IndexView, name='index'),

    # http://localhost/about/
    url(r'^about/$', views.AboutView, name='about'),

    # http://localhost/admissions/
    url(r'^admissions/$', views.AdmissionsView, name='admissions'),

    # http://localhost/dates/
    url(r'^dates/$', views.DatesView, name='dates'),

    # http://localhost/contact/
    url(r'^contact/$', views.ContactView, name='contact'),
]

main/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

main/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail, BadHeaderError
from django.core.mail import EmailMessage
from django.utils import timezone
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect


# Create your views here.
def IndexView(request):
    context = {
        'main': 'main'
    }
    return render(request, 'main/index.html', context)


def AboutView(request):
    context = {
        'main': 'main'
    }
    return render(request, 'main/about.html', context)


def AdmissionsView(request):
    context = {
        'main': 'main'
    }
    return render(request, 'main/admissions.html', context)


def DatesView(request):
    context = {
        'main': 'main'
    }
    return render(request, 'main/dates.html', context)


def ContactView(request):
    context = {
        'main': 'main'
    }

    if request.POST:
        name = request.POST['name']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']

        if subject and message and email:
            try:
                send_mail(
                    subject,
                    name + ' (' + email + ') says: ' + message,
                    email,
                    ['karisbrian1@gmail.com'],
                    fail_silently=False,
                )
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return HttpResponseRedirect('/contact/')
        else:
            # In reality we'd use a form class
            # to get proper validation errors.
            return HttpResponse('Make sure all fields are entered and valid.')

    return render(request, 'main/contact.html', context)

main/templates/main/about.html
{% extends 'main/base.html' %}

{% load staticfiles%}

{% block title %}Kidz Next Door School | About{% endblock %}

{% block hero %}
{% endblock %}

{% block content %}
<section id="grow">
  <div class="parallax-container">
    <div class="parallax hide-on-med-and-down"><img src="{% static 'main/images/abstract.png' %}" class="responsive-img" /></div>
    <div class="parallax hide-on-large-only"><img src="{% static 'main/images/12.jpg' %}" class="responsive-img" /></div>
  </div>
  <div class="section white">
    <div class="row container">
      <h2 class="header">Grow</h2>
      <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
    </div>
  </div>
</section>

<section id="play">
  <div class="parallax-container">
    <div class="parallax hide-on-med-and-down"><img src="{% static 'main/images/abstract1.jpg' %}" class="responsive-img" /></div>
    <div class="parallax hide-on-large-only"><img src="{% static 'main/images/13.jpg' %}" class="responsive-img" /></div>
  </div>
  <div class="section white">
    <div class="row container">
      <h2 class="header">Play</h2>
      <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
    </div>
  </div>
</section>

<section id="learn">
  <div class="parallax-container">
    <div class="parallax hide-on-med-and-down"><img src="{% static 'main/images/abstract4.jpg' %}" class="responsive-img" /></div>
    <div class="parallax hide-on-large-only"><img src="{% static 'main/images/15.jpg' %}" class="responsive-img" /></div>
  </div>
  <div class="section white">
    <div class="row container">
      <h2 class="header">Learn</h2>
      <p class="grey-text text-darken-3 lighten-3">Parallax is an effect where the background content or image in this case, is moved at a different speed than the foreground content while scrolling.</p>
    </div>
  </div>
</section>

<section id="gallery">
  <div class="parallax-container">
    <div class="parallax hide-on-med-and-down"><img src="{% static 'main/images/abstract3.jpg' %}" class="responsive-img" /></div>
    <div class="parallax hide-on-large-only"><img src="{% static 'main/images/14.jpg' %}" class="responsive-img" /></div>
  </div>
  <div class="section white">
    <div class="row container">
      <h2 class="header">Gallery</h2>
      <div class="slider">
        <ul class="slides">
          <li>
            <img src="{% static 'main/images/7.jpg' %}" />
            <div class="caption right-align">
              <h3>Classtime</h3>
              <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
          </li>
          <li>
            <img src="{% static 'main/images/8.jpg '%}" />
            <div class="caption left-align">
              <h3>School Trips</h3>
              <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
          </li>
          <li>
            <img src="{% static 'main/images/9.jpg' %}" />
            <div class="caption center-align">
              <h3>Sports Day</h3>
              <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
          </li>
          <li>
            <img src="{% static 'main/images/10.jpg' %}" />
            <div class="caption left-align">
              <h3>Graduation</h3>
              <h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
{% endblock %}

main/templates/main/admissions.html
{% extends 'main/base.html' %}

{% load staticfiles%}

{% block title %}Kidz Next Door School | Admissions{% endblock %}

{% block hero %}
{% endblock %}

{% block content %}
<section class="row section white">
  <article>
    <div class="col s12 m9" id="day-care">
      <div class="card medium blue accent-1">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="{% static 'main/images/book2.jpg' %}">
        </div>
        <div class="card-content">
          <span class="card-title activator text-darken-4">Day Care<i class="material-icons right">more_vert</i></span>
          <p><a href="{% static 'main/docs/KNDG Application for admission form.pdf' %}" download="Baby Class Admission Form">Download Admission Form</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Day Care<i class="material-icons right">close</i></span>
          <p>
            We consider play of utmost importance throughout the Early Learning Stages of a child. This level targets children between 2 to 3 years of age and are offered an opportunity to socialize, play and become integrated into the nursery environment. Other areas of focus are:
          </p>
            <li>Toilet training</li>
            <li>Communication</li>
            <li>Introduction to Basic language</li>
            <li>Preparations to writing (building finger muscles)</li>
          <p>
            The concepts your child will accrue from this level prepares them for Baby Class.
          </p>
        </div>
      </div>
    </div>
  </article>

  <article>
    <div class="col s12 offset-m3 m9" id="baby-class">
      <div class="card medium blue accent-1">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="{% static 'main/images/book5.jpg' %}">
        </div>
        <div class="card-content">
          <span class="card-title activator white-text text-darken-4">Baby Class<i class="material-icons right">more_vert</i></span>
          <p><a href="{% static 'main/docs/KNDG Application for admission form.pdf' %}" download="Baby Class Admission Form">Download Admission Form</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Baby Class<i class="material-icons right">close</i></span>
          <p>
            This level is for children between 3-4 years old. We will equip your child with knowledge that will ascertain they are able to pronounce the sounds (a-z) and numbers too. Speech and language is developed in an enjoyable way through storytelling and play. In addition, numeracy and literacy skills come through matching numbers, shapes and colors.  Motor skills are also developed at this stage through painting, cutting, tearing and using play dough. These skills will fully prepare your child for Middle Class (Nursery).
          </p>
        </div>
      </div>
    </div>
  </article>

  <article>
    <div class="col s12 m9" id="nursery">
      <div class="card large blue accent-1">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="{% static 'main/images/book.jpg' %}">
        </div>
        <div class="card-content">
          <span class="card-title activator text-darken-4">Nursery<i class="material-icons right">more_vert</i></span>
          <p><a href="{% static 'main/docs/KNDG Application for admission form.pdf' %}" download="Baby Class Admission Form">Download Admission Form</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Nursery<i class="material-icons right">close</i></span>
          <p>
            Here, we teach numbers and sound formation, handwriting, introduction to phonics, reading (sound &amp; Read book 1, key-words 1a-2a), coloring and pattern learning. "Look and say" words and phonics are introduced leading to 2 letter or 3 letter words.  Language and motor skills continue to develop and all these concepts learned are preparatory for the Pre-Unit level.
          </p>
        </div>
      </div>
    </div>
  </article>

  <article>
    <div class="col s12 offset-m3 m9" id="pre-primary">
      <div class="card large blue accent-1">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="{% static 'main/images/book3.jpg' %}">
        </div>
        <div class="card-content">
          <span class="card-title activator text-darken-4">Pre-Primary<i class="material-icons right">more_vert</i></span>
          <p><a href="{% static 'main/docs/KNDG Application for admission form.pdf' %}" download="Baby Class Admission Form">Download Admission Form</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Pre-Primary<i class="material-icons right">close</i></span>
          <p>
            This level is very important as it prepares the child for primary education – from class one onwards. Reading becomes fluent with practice and more advanced phonic work. Formal writing is introduced and hand control is now well established. Formal number work (addition and subtraction) is introduced, including general knowledge.
            <strong>At the end of the 3 year programme, each child should be developed to his or her full potential at this age.</strong>
          </p>
        </div>
      </div>
    </div>
  </article>

  <article>
    <div class="col s12 m9" id="primary">
      <div class="card large blue accent-1">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="{% static 'main/images/book1.jpg' %}">
        </div>
        <div class="card-content">
          <span class="card-title activator text-darken-4">Primary<i class="material-icons right">more_vert</i></span>
          <p><a href="{% static 'main/docs/KNDG Application for admission form.pdf' %}" download="Baby Class Admission Form">Download Admission Form</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">Primary<i class="material-icons right">close</i></span>
          <p>
            Kidz Next Door School recognizes that each child is an individual; that all children are creative; that all children need to succeed. Therefore, Kidz Next Door School in collaboration with parents and staff respects the individual needs of children; fosters a caring and creative environment; and emphasizes the social, emotional, physical, intellectual development of each child while respecting their gifts and talents.
            The School aims to provide a happy, caring and stimulating environment where children will recognize and achieve their fullest potential, so that they can make their best contribution to society.
            Pupils are encouraged to grow into well-educated, confident, self-disciplined young adults with the potential to be future leaders.<br />

            We work hand in hand with parents to ensure that the performance of their pupils, both in academic curriculum and life skills are of high quality.  We pride ourselves with highly trained and experienced personnel to ascertain they give their best to your child.
          </p>
        </div>
      </div>
    </div>
  </article>
</section>
{% endblock %}

main/templates/main/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en-us">
<head>
  <title>{% block title %}Kidz Next Door School {% endblock %}</title>
  <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Import fonts (Raleway, Lato) -->
  <link href="https://fonts.googleapis.com/css?family=Lato|Raleway" rel="stylesheet">

  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

  <!-- Master CSS -->
  <link rel="stylesheet" href="{% static 'main/css/master.css' %}" />

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

  {% block header %}
  <header class="transparent">
    <div class="navbar-fixed transparent">
      <nav class="indigo">
        <div class="nav-wrapper">
          <a href="{% url 'main:index' %}" class="brand-logo">KIDZ NEXT DOOR</a>
          <ul id="slide-out" class="side-nav">
            <li class="no-padding">
              <ul class="collapsible collapsible-accordion">
                <li>
                  <a class="collapsible-header">About
                    <i class="material-icons right">&#xE5C5;</i>
                  </a>
                  <div class="collapsible-body">
                    <ul>
                      <li><a href="{% url 'main:about' %}#grow">Grow</a></li>
                      <li><a href="{% url 'main:about' %}#play">Play</a></li>
                      <li><a href="{% url 'main:about' %}#learn">Learn</a></li>
                      <li><a href="{% url 'main:about' %}#gallery">Gallery</a></li>
                    </ul>
                  </div>
                </li>
              </ul>
            </li>
            <li class="no-padding">
              <ul class="collapsible collapsible-accordion">
                <li>
                  <a class="collapsible-header">Key Dates
                    <i class="material-icons right">&#xE5C5;</i>
                  </a>
                  <div class="collapsible-body">
                    <ul>
                      <li><a href="{% url 'main:dates' %}#!">Term I</a></li>
                      <li><a href="{% url 'main:dates' %}#!">Term II</a></li>
                      <li><a href="{% url 'main:dates' %}#!">Term III</a></li>
                    </ul>
                  </div>
                </li>
              </ul>
            </li>
            <li class="no-padding">
              <ul class="collapsible collapsible-accordion">
                <li>
                  <a class="collapsible-header">Admissions
                    <i class="material-icons right">&#xE5C5;</i>
                  </a>
                  <div class="collapsible-body">
                    <ul>
                      <li><a href="{% url 'main:admissions' %}#day-care">Day Care</a></li>
                      <li><a href="{% url 'main:admissions' %}#baby-class">Baby Class</a></li>
                      <li><a href="{% url 'main:admissions' %}#nursery">Nursery</a></li>
                      <li><a href="{% url 'main:admissions' %}#pre-primary">Pre-Primary</a></li>
                      <li><a href="{% url 'main:admissions' %}#primary">Primary</a></li>
                    </ul>
                  </div>
                </li>
              </ul>
            </li>
            <li><a href="{% url 'main:contact' %}">Contact Us</a></li>
          </ul>
          <ul class="right hide-on-med-and-down">
            <li><a class="dropdown-button" href="#!" data-activates="about">About
              <i class="material-icons right">&#xE5C5;</i>
            </a></li>
            <li><a class="dropdown-button" href="#!" data-activates="dates">Key Dates
              <i class="material-icons right">&#xE5C5;</i>
            </a></li>
            <li><a class="dropdown-button" href="#!" data-activates="admissions">Admissions
              <i class="material-icons right">&#xE5C5;</i>
            </a></li>
            <li><a href="{% url 'main:contact' %}">Contact Us</a></li>
            <ul id='about' class='dropdown-content'>
              <li><a href="{% url 'main:about' %}#grow">Grow</a></li>
              <li><a href="{% url 'main:about' %}#play">Play</a></li>
              <li><a href="{% url 'main:about' %}#learn">Learn</a></li>
              <li><a href="{% url 'main:about' %}#gallery">Gallery</a></li>
            </ul>
            <ul id='dates' class='dropdown-content'>
              <li><a href="{% url 'main:dates' %}#!">Term I</a></li>
              <li><a href="{% url 'main:dates' %}#!">Term II</a></li>
              <li><a href="{% url 'main:dates' %}#!">Term III</a></li>
            </ul>
            <ul id='admissions' class='dropdown-content'>
              <li><a href="{% url 'main:admissions' %}#day-care">Day Care</a></li>
              <li><a href="{% url 'main:admissions' %}#baby-class">Baby Class</a></li>
              <li><a href="{% url 'main:admissions' %}#nursery">Nursery</a></li>
              <li><a href="{% url 'main:admissions' %}#pre-primary">Pre-Primary</a></li>
              <li><a href="{% url 'main:admissions' %}#primary">Primary</a></li>
            </ul>
          </ul>
          <a href="#" data-activates="slide-out" class="button-collapse">
            <i class="material-icons">&#xE5D2;</i>
          </a>
        </div>
       </nav>
    </div>
  </header>
  {% endblock %}

  {% block hero %}
  <section class="row" id="hero">
    <div class="parallax-container">
      <div class="parallax hide-on-med-and-down"><img src="{% static 'main/images/4.jpg' %}" class="responsive-img" /></div>
      <div class="parallax hide-on-large-only"><img src="{% static 'main/images/11.jpg' %}" class="responsive-img" /></div>
    </div>
  </section>
  {% endblock %}

  {% block content %}
  {% endblock %}

  {% block footer %}
  <footer class="page-footer indigo">
    <div class="footer-copyright">
      <div class="container">
      &copy; 2016 Powered by StartUp Forest and Amplified Technologies
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>
  {% endblock %}

  <!-- jQuery3 -->
  <!-- <script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script> -->
  <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

  <script src="{% static 'main/js/master.js' %}"></script>
</body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% load staticfiles%}

{% block title %}Kidz Next Door School | Talk to Us!{% endblock %}

{% block hero %}
{% endblock %}

{% block content %}
<section class="section container">
  <div class="header">
    <h3 class="center-align">Talk to Us!</h3>
    <p class="flow-text center-align">
      Hello. If you have any questions or want to talk to us a bit more privately, send us a message and we'll get back to you soon. How soon? Very soon. We have a Customer Care team that's always ready to answer your questions anytime between working hours.
    </p>
  </div>

  <div class="row">
    <form class="col s12" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="input-field col s12 m6">
          <input name="name" type="text" class="validate" required />
          <label for="name">Name</label>
        </div>
        <div class="input-field col s12 m6">
          <input name="email" type="email" class="validate" required />
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input name="subject" type="text" class="validate" required />
          <label for="subject">Subject</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea name="message" class="materialize-textarea" required></textarea>
          <label for="message">Message</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <button class="btn waves-effect waves-light" type="submit" name="action">SEND
            <i class="material-icons right">&#xE163;</i>
          </button>
        </div>
      </div>
    </form>
  </div>
</section>
{% endblock %}

main/templates/main/dates.html
{% extends 'main/base.html' %}

{% load staticfiles%}

{% block title %}Kidz Next Door School | Key Dates{% endblock %}


{% block hero %}
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% load staticfiles%}

{% block content %}
<section>
  <div class="section white">
    <div class="row">
      <article class="col s12 m7">
        <h2 class="header">Welcome</h2>
        <p class="grey-text text-darken-3 lighten-3">
          Rusinga Schools are Christian day schools offering the British National Curriculum. We have a strong commitment to academic excellence, a high level of discipline and Christian values. Children are accepted from the age of two and are able to progress through our Kindergarten, Prep and Senior schools.

          At the end of each significant level when learners are transitioning from one Key Stage to another, assessments are conducted to check their level of attainment in various skills. At the end of Kindergarten, there is a Baseline Assessment in Numeracy and Literacy Skills. At Prep School, levels are divided into two: Key Stages 1 and 2.

          At the end of Key Stage 1 (Year 2), key skills are assessed in Numeracy and Literacy. At the end of Key Stage 2 (Year 6), key skills are assessed in Numeracy and Literacy.

          In Senior School, there are three Key Stages: Key Stage 3 (Years 7-9) where they sit Checkpoint Examinations that assess knowledge and skills in English, Mathematics and Science at the end of Year 9; Key Stage 4 (IGCSE-Years 10-11) where they sit IGCSEs in a number of subjects  and Key Stage 5 (Year 12 and 13) where they sit the GCE ‘A’ Level Examinations.

          We are a caring community, with high expectations in behaviour and work in an environment of tolerance, respect and cooperation.

          We are over 40 different nationalities represented at Rusinga. We involve parents in the education of their children and work in close partnership with a number of churches to support our pastoral care programmes.
        </p>
      </article>

      <article class="col s12 offset-m1 m4">
        <h4 class="header">Contacts</h4>
        <blockquote class="grey-text text-darken-3 lighten-3">
          P.O. Box 25088 – 00603 Lavington, Nairobi <br />
          Tel: +254 20 3872290, 3872395, 3872296 <br />
          Fax: +254 20 3862358 <br />
          Mobile: +254 722205341, 0733633723, 0733633724 <br />
          Email: info@rusinga.ac.ke <br />
          Email: recruitment@rusinga.ac.ke <br />
        </blockquote>
        <div class="divider"></div><br />
        <h4 class="header">KND on Map</h4>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1994.261671002775!2d36.974832450919465!3d-1.4598359999187673!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMcKwMjcnMzUuNCJTIDM2wrA1OCczMS42IkU!5e0!3m2!1sen!2ske!4v1465409134248" width="300" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
      </article>
    </div>
  </div>

  <div id="programmes" class="row">
    <h3 class="header center-align">Our Programmes</h3>
    <div class="divider"></div><br />

    <div class="col s12 m6">
      <a href="pages/admissions.html">
        <img src="{% static 'main/images/book2.jpg' %}" alt="" class="responsive-img card hoverable" />
        <div class="caption left-align">
          <h3>Baby Class/Play-Group</h3>
        </div>
      </a>
    </div>

    <div class="col s12 m6">
      <a href="pages/admissions.html">
        <img src="{% static 'main/images/book5.jpg' %}" alt="" class="responsive-img card hoverable" />
        <div class="caption left-align">
          <h3>Nursery</h3>
        </div>
        <a/>
    </div>

    <div class="col s12 m6">
      <a href="pages/admissions.html">
        <img src="{% static 'main/images/book.jpg' %}" alt="" class="responsive-img card hoverable" />
        <div class="caption left-align">
          <h3>Pre-Primary</h3>
        </div>
      </a>
    </div>

    <div class="col s12 m6">
      <a href="pages/admissions.html">
        <img src="{% static 'main/images/book3.jpg' %}" alt="" class="responsive-img card hoverable" />
        <div class="caption left-align">
          <h3>Primary</h3>
        </div>
      </a>
    </div>
  </div>
</section>
{% endblock %}